### ISSUE TITLE
Basic Example not working

### ISSUE THREAD

**Issue by baloodevil** [ging/licode#264]
Hello,
Trying to get basic example working.  After running through install scripts according to <a href="http://lynckia.com/licode/install.html">this</a>.  I can see the "toggle recording" page on 3001 but nothing happens.

When I run
<code>./licode/scripts/initLicode.sh</code>
it seems to start fine. Then 
<code>./licode/scripts/initBasicExample.sh</code> 
throws an error 
<code>Error: failed to connect to [localhost:27017]</code>
So I start mongo. Then try the command again, and get
<code>Error: listen EADDRINUSE</code>
Any help would be appreciated.

**Comment by mosfet1kg** [comment]
Turn on the mongodb 

sudo mongod --config /etc/mongodb.conf &

and then try again

**Comment by lodoyun** [comment]
Thanks @mosfet1kg.

**Comment by baloodevil** [comment]
Killing processes and starting mongo first solved the errors about used resources.  Thanks @mosfet1kg   Suggest updating install document to include starting mongo.

I assume the basic example is supposed to show something more than a disabled 'Toggle Recording' button.  The server process gives this info 
<code>INFO: NuveAuthenticator - [Auth] Unknow service: 54e948cce39dd09ea9b79b16</code>

**Comment by mosfet1kg** [comment]
Oh, come on...

It seems that you installed licode once again without removing it.

Licode saves its ​authentication tied up with NuVe info to mongodb.

Therefore, you should remove these info before you reinstall Licode.

<code>mongo</code>
<code>use nuvedb</code>
<code>db.dropDatabase()</code>

If you already installed licode, you don't need to install it all over again.

Please go to script folder and then excuted installNuve.sh. 

After that, you will able to see licode is working

**Comment by baloodevil** [comment]
Thanks @mosfet1kg for the response.  Dropping the database and running installNuve.sh resolved the NuveAuthenticator error.  According to console, it created a room, which is didn't do previously.  However, the webpage still only shows a disabled 'Toggle Recording' button.

Re-installing is a reasonable troubleshooting step when something you have no knowledge of doesn't seem to be working.  That may not be the correct move in this case, but is reasonable to expect a newbie to try.  I would suggest more documentation on setup and troubleshooting.  Newcomers don't have skills to troubleshoot modules they are not familiar with.  That would help with adoption if the install and docs were more robust.  I would be happy to contribute to docs once I know my way around the app.  First I need help getting started.  Any idea how to enable the 'Toggle Recording' button, or show whatever the Basic Example is supposed to demonstrate?

**Comment by nachoaguadoc** [comment]
Hi, have you granted access to your webcam in your browser? That should solve it. The recording button won't be active until you have any streams being published.

**Comment by baloodevil** [comment]
Thanks @nachoaguadoc.  That is probably the case.  However I am not able to get Chrome to allow access, more specifically to remember the selection.  I've read that remembering selection only works for https, so I opened https://localhost:3004 instead of the http://localhost:3001 referenced in the guide.  But that still doesn't seem to remember; possibly because the certificate is not trusted.  An issue for another forum.  And perhaps an amendment to the guide.  I'll spin up an EC2 instance and install everything and try from a public url.  Thanks for the support.

![screenshot](https://cloud.githubusercontent.com/assets/11354890/6607260/d7c1a6b2-c813-11e4-938b-cd63d587e70c.png)

**Comment by baloodevil** [comment]
Continuing to have problems getting this working.  I tried installing on EC2 and the installation fails.  Or at least Licode doesn't start properly.  When running initLicode.sh it gives the usual INFO messages, but then gets stuck in a loop which continuously launches new ErizoJS instances every second...
```
...
2015-03-12 14:30:00.561  - INFO: AMQPER - Queue ErizoAgent is open
Running process
2015-03-12 14:30:00.696  - INFO: ErizoAgent - Launched new ErizoJS  05e7d...
Running process
2015-03-12 14:30:00.881  - INFO: ErizoAgent - Launched new ErizoJS  c2e47...
Running process
2015-03-12 14:30:01.066  - INFO: ErizoAgent - Launched new ErizoJS  fbe66...
Running process
2015-03-12 14:30:01.250  - INFO: ErizoAgent - Launched new ErizoJS  d1578...
Running process
2015-03-12 14:30:01.442  - INFO: ErizoAgent - Launched new ErizoJS  e9d4b...
Running process
...repeat...
```

Here are <a href="https://drive.google.com/folderview?id=0B9lQe96ENgb4fmNZYzJ4WWZFUDJsbmQ1WXBtMWQtdjRNMDFDS1BtZFRnM1VqNjMwazlwcEk&usp=sharing">the logs</a> from each step of the install.  Any help on why this install doesn't work, while the one on my laptop does (even though I can't test it because of the Chrome microphone access issue) would be appreciated.  I'd really like to see this project working.

**Comment by ajithreddy** [comment]
any update on this problem of loop which continuously launches new ErizoJS instances every second.
